version="3.10.2"
project.git = true
maxColumn = 150
lineEndings = unix
importSelectors = singleLine
binPack.parentConstructors = false
danglingParentheses.callSite = true
runner.dialect = scala3

align.preset = more

rewriteTokens = {
  "⇒": "=>"
  "→": "->"
  "←": "<-"
}

align {
  tokens = [ {code = "=>", owner = "Case|Type.Arg.ByName"}, "=", "<-", "->", "%", "%%", "should", "shouldBe", "must" ]
  arrowEnumeratorGenerator = true
  openParenCallSite = false
  openParenDefnSite = false
}

spaces {
  beforeContextBoundColon = Never
  inImportCurlyBraces = false
}

continuationIndent {
  callSite = 2
  defnSite = 2
}

newlines {
  penalizeSingleSelectMultiArgList = false
  sometimesBeforeColonInMethodReturnType = true
  afterCurlyLambdaParams = keep
}

rewrite {
  scala3 = {
    convertToNewSyntax = true
    newSyntax.control = false
    removeOptionalBraces = false
  }
  rules = [RedundantBraces, RedundantParens, AsciiSortImports]
  redundantBraces {
    maxLines = 100
    includeUnitMethods = true
    stringInterpolation = true
    generalExpressions = false
    methodBodies = false
  }
}

project.excludeFilters = [
  ".*\\.sc$"
]
